# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.3.2
  docker: circleci/docker@1.5.0
  node: circleci/node@5.0.2

jobs:
  build_frontend:
    docker:
      - image: 'cimg/base:stable'
    resource_class: xlarge
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.18.0'
      - run:
          name: Build and export
          command: ( cd mage_ai/frontend && yarn install && yarn export )

  export_frontend:
    docker:
      - image: 'cimg/base:stable'
    resource_class: xlarge
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.18.0'
      - add_ssh_keys:
          fingerprints:
            - "50:0e:ac:20:b8:b0:c0:65:80:77:5b:43:9b:b4:50:a1"
      - run:
          name: Checkout to current branch
          command: |
            git fetch origin
            git config user.email "ci@mage.ai"
            git config user.name "Circle CI"
            git checkout $CIRCLE_BRANCH
      - run:
          name: Build and export
          command: ( cd mage_ai/frontend && yarn install && yarn export_prod )
      - run:
          name: Build and export base path version
          command: |
            mv mage_ai/frontend/next_base_path.config.js mage_ai/frontend/next.config.js
            ( cd mage_ai/frontend && yarn install && yarn export_prod_base_path )
      - run:
          name: Update frontend build
          command: |
            git add mage_ai/server/frontend_dist
            git add mage_ai/server/frontend_dist_base_path_template
            git commit -m "[CI] Update frontend build"
            git push origin $CIRCLE_BRANCH

workflows:
  build_and_export:
    jobs:
      - build_frontend
      - hold:
          type: approval
          requires:
            - build_frontend
          filters:
            branches:
              only:
                - master
                - alpha
      - export_frontend:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
                - alpha
